import './globals.css'
import { Montserrat } from 'next/font/google'
import MyProvider from '@/redux/MyProvider'
import { MyTooltipContainer, MyPopoverContainer } from '@/components'

const montserrat = Montserrat({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  style: ['normal', 'italic'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <MyProvider>
          {children}
          <MyTooltipContainer />
          <MyPopoverContainer />
        </MyProvider>
      </body>
    </html>
  )
}
